config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :issues
  resources :users
  resources :comments
  resources :attachments
  
  get 'auth/:provider/callback', to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'home/show'

  post '/issues' =>"issues#create", as: :create
  post '/issues/:id/watch' => "issues#watch", as: :watch
  post '/issues/:id/unwatch' => "issues#unwatch", as: :unwatch
  
  post '/issues/:id/vote' => "issues#vote", as: :vote
  post '/issues/:id/unvote' => "issues#unvote", as: :unvote
  
  put '/issues/:id/status' => "issues#status", as: :status
  
  #root 'issues#index'
  root to: "home#show"
  
  
  get '/issues/:Issue_id/comments' => "comments#getByIssue", as: :getByIssue
  post '/issues/:Issue_id/comments' => "comments#postOnIssue", as: :postOnIssue
  get '/issues/:Issue_id/attachments' => "attachments#findByIssue", as: :findByIssue

end

app/models/issue.rb
class Issue < ApplicationRecord
    validates :title, presence: true, length: { maximum: 140 }
    validates :description, length: { maximum: 300 }
    belongs_to :creator, class_name: 'User'
    belongs_to :assignee, optional: true, class_name: 'User'
    has_many :comments
    has_many :attachments
    has_and_belongs_to_many :watchers, class_name: 'User'
    has_many :votos, dependent: :destroy
    
    scope :status, -> (status) { where(status: status) if status.present? }
    scope :priority, -> (priority) { where(priority: priority) if priority.present? }
    scope :type_issue, -> (type_issue) { where(type_issue: type_issue) if type_issue.present? }
    scope :assignee_id, -> (assignee_id) { where(assignee_id: assignee_id) if assignee_id.present? }
    
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  include SessionsHelper
  #before_action :logged_in_user
  skip_before_action :verify_authenticity_token
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
  $s = ""
  $pi = ""
  $t = ""
  $a = ""
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all.order(sort_column + " " + sort_direction)
    if params[:status].present? and params[:status].length != 2
      $s = params[:status].join
    end
    if params[:priority].present?
      $pi = params[:priority].join
    end
    if params[:type_issue].present?
      $t = params[:type_issue].join
    end 
    if params[:assignee_id].present?
      $a = params[:assignee_id].join
    end
    
    if (not params[:assignee_id].present?) and (not params[:type_issue].present?) and (not params[:priority].present?) and (not params[:status].present?)
      $s = ""
      $pi = ""
      $t = ""
      $a = ""
    end
    if params[:status].present? and params[:status].length == 2
      $s = "new","open"
    end
    if params[:status].present? and params[:status].length != 2 and params[:status].join == "unresolved"
      $s = "new","open"
    end
    
    
    @issues = @issues.status($s).priority($pi).type_issue($t).assignee_id($a)
    if params.has_key?(:watcher)
      @issues = User.find(params[:watcher]).watched
    end
    er=false
    @user_aux = authenticate
    if(@user_aux.nil?)
     er=true
    else
      if params.has_key?(:watching)
        @issues = User.find(@user_aux.id).watched
      end
    end
    
    if(er == true)
      respond_to do |format|
        format.json {render json: {meta: {code: 401, error_message: "Unauthorized"}}, status: :unauthorized}
      end
    else 
      respond_to do |format|   
        format.html
        format.json {render json: @issues, status: :ok, each_serializer: IssueSerializer}
      end
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    respond_to do |format|
      format.html
      format.json {render json: @issue, status: :ok, serializer: IssueSerializer}
    end
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    if(current_user.nil?)
      token2 = request.headers['token']
      if(token2)
        @user_aux = authenticate
        if(@user_aux.nil?)
          render json: { meta: {code: 401, error_message: "Invalid token"}}
        else
          request_parameters = JSON.parse(request.body.read.to_s)
          title = request_parameters["text"]
          details = request_parameters["details"]
          type = request_parameters["type"]
          priority = request_parameters["Priority"]
          assignee = request_parameters["Assignee"]
          
          if not ["bug", "enhancement", "proposal", "task"].include?(type)
            render json: { error_message: "Type must be one of: bug, enhancement, proposal, task"}, status: 403
          return
          end
          if not ["trivial", "minor", "major", "critical", "blocker"].include?(priority)
            render json: { error_message: "Priority must be one of: trivial, minor, major, critical, blocker"}, status: 403
          return
          end
          if assignee == 0
             @issue = Issue.create(title: title, description: details, type_issue: type, priority: priority, creator_id: @user_aux.id, status:"new")
          else
            assignee_aux = User.find(assignee)
            if(assignee_aux)
              @issue = Issue.create(title: title, description: details, type_issue: type, priority: priority, creator_id: @user_aux.id, assignee_id: assignee,status:"new")
            else
              error = true
            end
          end 
          
          if(error == true)
            render json: { meta: {code: 401, error_message: "Invalid Assignee"}}
          else
            if @issue.save
              respond_to do |format|
                format.json {render json: @issue, status: :created, serializer: IssueSerializer}
              end
            else
              render json: @issue.errors, status: :unprocessable_entity
            end
          end
        end
      else 
        render json: {
          error: "Missing token in header",
          status: 401
        },status: 400
      end
    
    else
      @issue = Issue.new(issue_params)
      respond_to do |format|
        if @issue.save
          format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
          format.json { render :show, status: :created, location: @issue }
        else
          format.html { render :new }
          format.json { render json: @issue.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    comment_text = ""
    if(current_user.nil?)
      token2 = request.headers['token']
      if(token2)
        @user_aux = authenticate
        if(@user_aux.nil?)
          render json: { error_message: "Invalid token"}, status: 401
        else
          request_parameters = JSON.parse(request.body.read.to_s)
          title = request_parameters["title"]
          details = request_parameters["details"]
          type = request_parameters["type"].downcase
          priority = request_parameters["Priority"].downcase
          assignee = request_parameters["Assignee"]
          status = request_parameters["Status"].downcase
          
          if not ['new', 'open','on hold','resolved','duplicate','invalid','wontfix','closed'].include?(status)
            render json: { error_message: "status must be one of: new, open, on hold, resolved,duplicate, invalid,wontfix,closed"}, status: 403
            return
          else
            if (status !="" and status != @issue.status) 
              comment_text +="changed status to " + status + "<br>"
            else
              status = @issue.status
            end
          end
          
          if (title != "" and title != @issue.title) 
            comment_text = comment_text + "changed title to " + title + "<br>"
          else 
            title = @issue.title
          end
          
          if not ["bug", "enhancement", "proposal", "task"].include?(type)
            render json: { error_message: "Type must be one of: bug, enhancement, proposal, task"}, status: 403
            return
          else
            if (type != "" and type != @issue.type_issue)
              comment_text = comment_text + "marked as " + type + "<br>"
            else
              type = @issue.type_issue
            end
          end
          
          if not ["trivial", "minor", "major", "critical", "blocker"].include?(priority)
            render json: { error_message: "Priority must be one of: trivial, minor, major, critical, blocker"}, status: 403
            return
          else
            if (priority != "" and priority != @issue.priority)
              comment_text = comment_text + "marked as " + priority + "<br>"
            else
              priority = @issue.priority
            end
          end
          
          if (assignee != -1  and assignee != @issue.assignee_id  )
            comment_text = comment_text + "assigned issue to " + User.find(assignee).name + "<br>"
          elsif (assignee == -1)
            assignee = nil
          else 
            assignee = @issue.assignee_id
          end
          if (details != "" and details != @issue.description) 
            comment_text = comment_text + "edited description" + "<br>"
          else 
            details = @issue.description
          end
          if (comment_text != "")
            Comment.create(:text => comment_text, :reporter_id => @user_aux.id, :issue_id => @issue.id)
          end
          if @issue.update(title: title, description: details, type_issue: type, priority: priority, creator_id: @user_aux.id, assignee_id: assignee, status: status)
              render json: @issue, status: :ok, each_serializer: IssueSerializer
          else
              render json: @issue.errors, status: 404
          end
          
        end
      else 
        render json: {
          error: "Missing token in header",
          status: 401
        },status: 401
      end
    
    else
      
      if (issue_params[:status].present? and issue_params[:status] != @issue.status) 
        comment_text +="changed status to " + issue_params[:status] + "<br>"
      end
      if (issue_params[:title].present? and issue_params[:title] != @issue.title) 
        comment_text = comment_text + "changed title to " + issue_params[:title] + "<br>"
      end
      if (issue_params[:type_issue].present? and issue_params[:type_issue] != @issue.type_issue)
        comment_text = comment_text + "marked as " + issue_params[:type_issue] + "<br>"
      end
      if (issue_params[:priority].present? and issue_params[:priority] != @issue.priority)
        comment_text = comment_text + "marked as " + issue_params[:priority] + "<br>"
      end
      if (issue_params[:assignee_id].present? and issue_params[:assignee_id] != @issue.assignee_id)
        comment_text = comment_text + "assigned issue to " + User.find(issue_params[:assignee_id]).name + "<br>"
      end
      if (issue_params[:description].present? and issue_params[:description] != @issue.description) 
        comment_text = comment_text + "edited description" + "<br>"
      end
      if (comment_text != "")
        Comment.create(:text => comment_text, :reporter_id => current_user.id, :issue_id => @issue.id)
      end
      respond_to do |format|
        if @issue.update(issue_params)
          format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
          format.json { render :show, status: :ok, location: @issue }
        else
          format.html { render :edit }

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field  :title, id: :issue_title, class: "ampliar" %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :issue_description, class: "ampliar" %>
    </div>
  
   <div class="field">
      <%= form.label :assignee_id %>
      <%= form.select(:assignee_id, options_from_collection_for_select(User.all, :id, :name), prompt: "Select user") %>
    </div>
    
    <div class="field">
      <%= form.label "Type" %>
      <%= form.select :type_issue, ['bug', 'enhancement','proposal','task']%>
    </div>
  
    <div class="field">
      <%= form.label :priority %>
      <%= form.select :priority, ['trivial', 'minor','major','critical','blocker']%>
    </div>
  
    <div class="field">
      <%= form.hidden_field :status, id: :issue_status, value: "new" %>
    </div>
    
    <div class="field">
      <%= form.hidden_field :votes, id: :issue_votes, value: 0 %>
    </div>
  
    <div class="field">
      <%= form.hidden_field :creator_id, id: :issue_creator_id, value: current_user.id %>
    </div>
    
    <br>
  
    <div class="actions">
      <%= form.submit %>
      <span>&nbsp &nbsp &nbsp &nbsp</span>
      <%= link_to '<button class="buttonB" type="button">Back</button>'.html_safe, issues_path %>
    </div>

<% end %>

app/views/issues/_formEdit.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field  :title, id: :issue_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :issue_description %>
  </div>

  <div class="field">
    <p> Creator </p>
  </div>
  <div>
    <a href="/users/<%= issue.creator_id %>">
      <%= image_tag( User.all.find(issue.creator_id).foto, width: 25, height: 25, class: 'img-circle') %>
      <span><%= User.all.find(issue.creator_id).oauth_token %></span>
    </a>
  </div>
  
  <br/>
  
  <div class="field">
    <%= form.label :assignee_id %>
    <%= form.select(:assignee_id, options_from_collection_for_select(User.all, :id, :name), prompt: "Select user") %>
  </div>
  
  <div class="field">
    <%= form.label "Type" %>
    <%= form.select :type_issue, ['bug', 'enhancement','proposal','task']%>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, ['trivial', 'minor','major','critical','blocker']%>
  </div>

  <div class="actions">
    <%= form.submit %>
    <span>&nbsp &nbsp &nbsp &nbsp</span>
    <%= link_to '<button class="buttonB" type="button">Back</button>'.html_safe, issues_path %>
  </div>

<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>
<br>
<%= render 'formEdit', issue: @issue %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<p class="p" >Filter by: &nbsp <%= link_to '<button class="filter" type="button">All</button>'.html_safe, issues_path %> 
&nbsp <%= link_to '<button class="filter" type="button">Unresolved</button>'.html_safe, issues_path(:status => ['new','open']) %>
&nbsp <%= link_to '<button class="filter" type="button">My Issues</button>'.html_safe, issues_path(:assignee_id => [ current_user.id ]) %>  
&nbsp <%= link_to '<button class="filter" type="button">Watching</button>'.html_safe, issues_url(watcher: current_user.id) %> </p>

<% if $t != "" %>
  <span> <b> Type:</b> <%= $t %> </span>
<% end %>

<% if $pi != "" %>
  <span><b> Priority:</b> <%= $pi %> </span> 
<% end %>

<% if $s != "" and $s.length != 2 %>
  <span><b> Status:</b> <%= $s %> </span>
<% end %>

<% if $s != "" and $s.length == 2 %>
  <span><b> Status:</b> <%= $s[0] %>, <%= $s[1] %> </span>
<% end %>

<% if $a != "" %>
  <span style="margin-bottom: 10px"><b> Assignee:</b> <%= User.all.find($a).name %> </span>
<% end %>

<table class="hoverTable" id="customers" >
  <thead class = hoverTableHeader>
    <tr>
      <th><%= sortable "id", "Title" %></th>
      <th><%= sortable "type_issue", "Type" %></th>
      <th><%= sortable "priority", "Priority" %></th>
      <th><%= sortable "status", "Status" %></th>
      <th><%= sortable "votes", "Votes" %></th>
      <th><%= sortable "assignee_id", "Assignee" %></th>
      <th><%= sortable "created_at", "Created" %></th>
      <th><%= sortable "updated_at", "Updated" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        
        <td><%= link_to "#"+issue.id.to_s+": "+issue.title, issue %></td>
        
        <% if issue.type_issue == 'bug' %>
          <td><%= link_to image_tag('bug.svg', width: 15, height: 15), issues_path(:type_issue => [issue.type_issue], :priority => [$pi], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.type_issue == 'task' %>
          <td><%= link_to image_tag('task.svg', width: 15, height: 15), issues_path(:type_issue => [issue.type_issue], :priority => [$pi], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.type_issue == 'enhancement' %>
          <td><%= link_to image_tag('enhancement.svg', width: 15, height: 15), issues_path(:type_issue => [issue.type_issue], :priority => [$pi], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.type_issue == 'proposal' %>
          <td><%= link_to image_tag('proposal.svg', width: 15, height: 15), issues_path(:type_issue => [issue.type_issue], :priority => [$pi], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.priority == 'blocker' %>
          <td><%= link_to image_tag('blocker.svg', width: 15, height: 15), issues_path(:type_issue => [$t], :priority => [issue.priority], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.priority == 'critical' %>
          <td><%= link_to image_tag('critical.svg', width: 15, height: 15), issues_path(:type_issue => [$t], :priority => [issue.priority], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.priority == 'major' %>
          <td><%= link_to image_tag('major.svg', width: 15, height: 15), issues_path(:type_issue => [$t], :priority => [issue.priority], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.priority == 'minor' %>
          <td><%= link_to image_tag('minor.svg', width: 15, height: 15), issues_path(:type_issue => [$t], :priority => [issue.priority], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>
        
        <% if issue.priority == 'trivial' %>
          <td><%= link_to image_tag('trivial.svg', width: 15, height: 15), issues_path(:type_issue => [$t], :priority => [issue.priority], :status => [$s], :assignee_id => [$a]) %></td>
        <%end%>

        <td><%= link_to issue.status, issues_path(:type_issue => [$t], :priority => [$pi], :status => [issue.status], :assignee_id => [$a]) %></td>
        <td><%= issue.votos.size %></td>
        <% if issue.assignee_id != nil %>
          <td><%= link_to image_tag(User.all.find(issue.assignee_id).foto, width: 20, height: 20,class: 'img-circle'), issues_path(:type_issue => [$t], :priority => [$pi], :status => [$s], :assignee_id => [issue.assignee_id])%><%= User.all.find(issue.assignee_id).name %></td>
        <% else %>
           <td></td>
        <% end %>
        <td><%= issue.created_at.in_time_zone('Madrid').to_formatted_s(:long) %></td>
        <td><%= issue.updated_at.in_time_zone('Madrid').to_formatted_s(:long) %></td>
        <% if issue.watchers.exists?(:id => current_user.id) %>
          <td><%= link_to image_tag('watching.svg', width: 20, height: 20), unwatch_url(id: issue.id),  method: :unwatch %></td>
        <% else %>
           <td><%= link_to image_tag('not-watching.svg', width: 20, height: 20), watch_url(id: issue.id),  method: :watch  %></td>
        <% end %>
        <!-- <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button class="buttonC" type="button">Create Issue</button>'.html_safe, new_issue_path %>

app/views/issues/new.html.erb
<br>
<h2>Issues</h2>
<br>
<h3>Create Issue</h3>
<br>
<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<div id="content">
  <div class="sidebar">
      <div class="issue_toolbar">
        <%= form_with(model: @issue, local: true) do |form| %>
          <%= form.select :status, ['new', 'open','on hold','resolved','duplicate','invalid','wontfix','closed'], {}, { value: @issue.status, class: 'form-control', onchange: 'this.form.submit();' } %>
        <% end %>
      </div>
      <div class="sidebar_info">
        <p>
        <strong>Assignee:</strong>
          <% if @issue.assignee_id != nil %>
            <%= User.all.find(@issue.assignee_id).name %>
          <% else %>
            <%= "-" %>
          <% end %>
        </p>
        <p>
          <strong>Type:</strong>
          <%= @issue.type_issue %>
        </p>
        <p>
          <strong>Priority:</strong>
          <%= @issue.priority %>
        </p>
        <p>
          <strong>Status:</strong>
          <%= @issue.status %>
        </p>
        <p>
          <strong>Votes:</strong>
          <%= @issue.votos.size %>
          <% if Voto.where(:user_id => current_user.id, :issue_id => params[:id]).take == nil %>
          <span><%= link_to 'Vote for this issue', vote_url(id: @issue.id),  method: :vote  %></span>
          <% else %>
           <span><%= link_to 'Remove vote', unvote_url(id: @issue.id),  method: :unvote  %></span>
          <% end %>
        </p>
        <p>
          <strong>Watchers:</strong>
          <%= @issue.watchers.size %>
          <% 
          begin
          @issue.watchers.find(current_user.id)
          rescue ActiveRecord::RecordNotFound => msg
          end
          if msg != nil %>
          <span><%= link_to 'Watch this issue', watch_url(id: @issue.id),  method: :watch  %></span>
          <% else %>
           <span><%= link_to 'Stop watching', unwatch_url(id: @issue.id),  method: :unwatch  %></span>
          <% end %>
        </p>
      </div>
      
      <%= link_to '<button class="buttonB" type="button">Edit</button>'.html_safe, edit_issue_path(@issue) %>
      <span>&nbsp &nbsp &nbsp &nbsp</span>
      <%= link_to '<button class="buttonB" type="button">Delete</button>'.html_safe, @issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
  </div>
  <header>
    <h1>
      <span> <%= @issue.title %> </span>
    </h1>
  </header>
  <div>
    <div>
      <span> Issue #<%= @issue.id %> </span>
      <span><%= @issue.status %></span> 
      <br>
    </div>
    <div class="item">
      <div id="issue_main_content">
        <div class="issue_author">
          <a href="/users/<%= @issue.creator_id %>">
            <%= image_tag( User.all.find(@issue.creator_id).foto, width: 25, height: 25, class: 'img-circle') %>
            <span><%= User.all.find(@issue.creator_id).name %></span>
          </a>
          created an issue
          <time>x days ago</time>
        </div>
        <div class="issue_description">
          <p><%= @issue.description %></p>
        </div>
        <div class="attachments">
          <% @issue.attachments.each do |attachment| %>
            <!--img src="https://cdn2.iconfinder.com/data/icons/attachment/154/attach-clip-round-function-ui-512.png" alt="Smiley face" height="42" width="42"-->
            <span class="borde">
              <%= link_to attachment.file_file_name, attachment.file.url, target: '_blank', class: "attachmentLink" %>
              <%= link_to 'X', attachment, method: :delete, data: { confirm: 'Are you sure?' }, class: "deleteSymbol" %>
            </span>
          <% end %>
        </div>
      </div>
      <div id="issue_comments_container">
        <h2>Comments(<%= @issue.comments.length %>)</h2>
        <% @issue.comments.each do |comment| %>
          <div class="comment">
            <div class="comment_author">
              <a href="/users/<%= comment.reporter_id %>">
                <%= image_tag( User.all.find(comment.reporter_id).foto, width: 25, height: 25, class: 'img-circle') %>
                <span><%= User.all.find(comment.reporter_id).name %></span>  
              </a>
            </div>
            <p><%= raw(comment.text) %></p>
            <div>
              <p class="comment_toolbar">
                <% if current_user.id == comment.reporter_id %>
                  <%= link_to 'Edit', edit_comment_path(comment) %>
                <% end %>
                <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
              </p>
            </div>
          </div>
        <% end %>
      </div>
      <div>
        <%= form_for :comment, url: "/comments", method: "post" do |f| %>
          <%= f.text_area :text, id: :comment_text %>
          <%= f.hidden_field :issue_id, id: :comment_issue_id, value: @issue.id %>
          <%= f.hidden_field :reporter_id, id: :comment_reporter_id, value: current_user.id %>
          <%= f.submit %>
        <% end %>
      </div>
      <br>
      <div class="add_attachments">
        <h2>Add attachments</h2>
        <%= form_for :attachment, url: "/attachments", method: "post" do |f| %>
          <%= f.file_field :file %>
          <%= f.hidden_field :issue_id, id: :attachment_issue_id, value: @issue.id %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br><br>
<%= link_to '<button class="buttonB" type="button">Back</button>'.html_safe, issues_path %>