config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :issues
  resources :users
  resources :comments
  resources :attachments
  
  get 'auth/:provider/callback', to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'home/show'

  post '/issues' =>"issues#create", as: :create
  post '/issues/:id/watch' => "issues#watch", as: :watch
  post '/issues/:id/unwatch' => "issues#unwatch", as: :unwatch
  
  post '/issues/:id/vote' => "issues#vote", as: :vote
  post '/issues/:id/unvote' => "issues#unvote", as: :unvote
  
  put '/issues/:id/status' => "issues#status", as: :status
  
  #root 'issues#index'
  root to: "home#show"
  
  
  get '/issues/:Issue_id/comments' => "comments#getByIssue", as: :getByIssue
  post '/issues/:Issue_id/comments' => "comments#postOnIssue", as: :postOnIssue
  get '/issues/:Issue_id/attachments' => "attachments#findByIssue", as: :findByIssue

end

app/models/attachment.rb
class Attachment < ApplicationRecord
  
  belongs_to :issue
  
  #Mounts paperclip file
  has_attached_file :file
  
  #Use this if you do not want to validate the uploaded file type.
  do_not_validate_attachment_file_type :file

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  include SessionsHelper
  #before_action :logged_in_user
  skip_before_action :verify_authenticity_token
  
  #Index action, attachments gets listed in the order at which they were created
 def index
  @attachments = Attachment.all
  render json: @attachments, status: :ok, each_serializer: AttachmentSerializer
 end
 
 def findByIssue
  @attachments = Attachment.all.where(issue_id: params[:Issue_id])
  #render json: @attachments.to_json() 
  render json: @attachments, status: :ok, each_serializer: AttachmentSerializer
 end

 #New action for creating a new attachment
 def new
  @attachment = Attachment.new
 end
 
 #Create action ensures that submitted attachment gets created if it meets the requirements
 def create
  @attachment = Attachment.new(attachment_params)
  if @attachment.save
   id_isue = @attachment.issue_id.to_s
   flash[:notice] = "Successfully added new attachment!"
   redirect_to "/issues/" + id_isue
  else
   flash[:alert] = "Error adding new attachment!"
   render :new
  end
 end
 
 #Destroy action for deleting an already uploaded image
  def destroy
    @attachment = Attachment.find(params[:id])
    if(current_user.nil?)
      token2 = request.headers['token']
      if(token2)
        @user_aux = authenticate
        if(@user_aux.nil?)
          render json: { meta: {code: 401, error_message: "Invalid token"}}
        else
          if @attachment.destroy
            render json: {message: "success"}, status: 204
          else
            render json: { meta: {code: 422, error_message: "Unprocessable Entity"}}
          end
        end
      else
        render json: { error: "Missing token in header",status: 401 },status: 400
      end
    else
      if @attachment.destroy
        id_isue = @attachment.issue_id.to_s
        flash[:notice] = "Successfully deleted attachment!"
        redirect_to "/issues/" + id_isue
      else
        flash[:alert] = "Error deleting attachment!"
      end
    end
  end
 
 private

 #Permitted parameters when creating an attachment. This is used for security reasons.
 def attachment_params
  params.require(:attachment).permit(:title, :issue_id, :file)
 end
 
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/index.html.erb
<div class="page-header"><h1>Upload File</h1></div>

<div class="media">
  <% @attachments.each do |attachment| %>
    <p><%= attachment.issue_id %></p>
    <%= link_to attachment.file.url, attachment.file.url, target: '_blank' %>
  <% end %>
</div>

app/views/attachments/new.html.erb
<div class="page-header"><h1>Upload File</h1></div>

<%= form_for @attachment, url: attachments_path, html: { multipart: true } do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@attachment.errors.count, "error")} prohibited this attachment from being saved:" %>
      </h2>
      <ul>
        <% @attachment.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= text_field :title, id: :attachment_title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>

  <div class="field">
    <%= f.submit 'Upload Attachment' %>
  </div>
<% end %>