config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :issues
  resources :users
  resources :comments
  resources :attachments
  
  get 'auth/:provider/callback', to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'home/show'

  post '/issues' =>"issues#create", as: :create
  post '/issues/:id/watch' => "issues#watch", as: :watch
  post '/issues/:id/unwatch' => "issues#unwatch", as: :unwatch
  
  post '/issues/:id/vote' => "issues#vote", as: :vote
  post '/issues/:id/unvote' => "issues#unvote", as: :unvote
  
  put '/issues/:id/status' => "issues#status", as: :status
  
  #root 'issues#index'
  root to: "home#show"
  
  
  get '/issues/:Issue_id/comments' => "comments#getByIssue", as: :getByIssue
  post '/issues/:Issue_id/comments' => "comments#postOnIssue", as: :postOnIssue
  get '/issues/:Issue_id/attachments' => "attachments#findByIssue", as: :findByIssue

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--TOTA LA INTERFICIE GRAFICA QUE ES MOSTRARA EN TOT MOMENT, VEURE YIELD AL FINAL-->

<html>
  <head>
    <title>IssueTracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!--Ultima versio de CSS
  <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!--Opcional (Theme)
  <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
  <!--Ultima versio de Javascript
  <script src = "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>-->
  
  </head>
  <body>
      <div id = "BarraSuperior">
        <!--Brand i Toggle agrupats per millorar el display en movils -->
        <div id = "BarraSuperior-Left">
          <%if current_user %>
            <h1 id = "mainBtn"><%= link_to signout_path do %><%= image_tag('exitbueno.png', width: 51, height: 51) %><% end %></h1>
          <%end%>
        </div>
        
        <!--Obtenir els nav links i les forms per fer toggling-->
        <div id = "BarraSuperior-Right">
          <% if current_user %>
            <div id = "BarraSuperior-Right-Pic"><%= image_tag(current_user.foto, width: 51, height: 51, class: 'img-circle') %></div>
            <div id = "BarraSuperior-Right-LoggedIn">Signed in as: <%= current_user.name %></div>
          <% else %>
              <div id = "BarraSuperior-Right-Pic"><%= link_to image_tag('logoASW.png', width: 220, height: 51), "/auth/google_oauth2", id: "sign_in" %></div>
          <% end %>
        </div> 
      </div>
    
    
    <%= yield %>
    
  </body>
</html>